<a href="https://colab.research.google.com/github/caghamohammadi/Tensorflow_tutorial/blob/main/Session_15_Creating_your_first_tensors_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **PART 1**

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor_example = tf.constant([ [[1,2],[3,4]] , [[1,2],[4,5]] , [[1,2],[6,7]] ])
tensor_example

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [6, 7]]], dtype=int32)>

In [ ]:
tensor_example.ndim

3

In [ ]:
constant_tensor = tf.constant([2,3])
changable_tensor = tf.Variable([2,3])



constant_tensor, changable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(5)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 3], dtype=int32)>

In [ ]:
g = tf.random.Generator.from_seed(1234)
g_1 = g.normal(shape=(3,2))

g_p = tf.random.Generator.from_seed(1234)
g_p_1 = g_p.normal(shape=(3,2))

g_1,g_p_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.9356609 ,  1.0854305 ],
        [-0.93788373, -0.5061547 ],
        [ 1.3169702 ,  0.7137579 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.9356609 ,  1.0854305 ],
        [-0.93788373, -0.5061547 ],
        [ 1.3169702 ,  0.7137579 ]], dtype=float32)>)

In [57]:
not_shuffled_tensor = tf.constant([[1,2],[3,4],[5,6]])

tf.random.set_seed(43)
shuffled_tensor =tf.random.shuffle(not_shuffled_tensor, seed=42)
not_shuffled_tensor, shuffled_tensor

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>)

In [58]:
tf.ones([4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [59]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [67]:
import numpy as np

A = np.arange(1,16)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
T_A = tf.constant(A,shape=(3,5))
T_A

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])>

### **PART 2**

In [70]:
tf_4D = tf.zeros([2,2,3,4])
tf_4D

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [72]:
tf_4D[0,0]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [74]:
tf_4D.ndim, tf_4D.shape, tf.size(tf_4D).numpy()

(4, TensorShape([2, 2, 3, 4]), 48)

In [76]:
t_2D = tf.Variable([[1,2],[3,4]])
t_2D

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [78]:
E_1 = tf.Variable([[1,2],[3,4]])
E_1 + 10 , E_1 * 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>)