<a href="https://colab.research.google.com/github/caghamohammadi/Tensorflow_tutorial/blob/main/Session_15_Creating_your_first_tensors_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **PART 1**

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor_example = tf.constant([ [[1,2],[3,4]] , [[1,2],[4,5]] , [[1,2],[6,7]] ])
tensor_example

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [6, 7]]], dtype=int32)>

In [9]:
tensor_example.ndim

3

In [10]:
constant_tensor = tf.constant([2,3])
changable_tensor = tf.Variable([2,3])



constant_tensor, changable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [11]:
changable_tensor[0].assign(5)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 3], dtype=int32)>

In [12]:
g = tf.random.Generator.from_seed(1234)
g_1 = g.normal(shape=(3,2))

g_p = tf.random.Generator.from_seed(1234)
g_p_1 = g_p.normal(shape=(3,2))

g_1,g_p_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.9356609 ,  1.0854305 ],
        [-0.93788373, -0.5061547 ],
        [ 1.3169702 ,  0.7137579 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.9356609 ,  1.0854305 ],
        [-0.93788373, -0.5061547 ],
        [ 1.3169702 ,  0.7137579 ]], dtype=float32)>)

In [13]:
not_shuffled_tensor = tf.constant([[1,2],[3,4],[5,6]])

tf.random.set_seed(43)
shuffled_tensor =tf.random.shuffle(not_shuffled_tensor, seed=42)
not_shuffled_tensor, shuffled_tensor

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>)

In [14]:
tf.ones([4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
import numpy as np

A = np.arange(1,16)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
T_A = tf.constant(A,shape=(3,5))
T_A

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])>

### **PART 2**

In [18]:
tf_4D = tf.zeros([2,2,3,4])
tf_4D

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
tf_4D[0,0]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [20]:
tf_4D.ndim, tf_4D.shape, tf.size(tf_4D).numpy()

(4, TensorShape([2, 2, 3, 4]), 48)

In [21]:
t_2D = tf.Variable([[1,2],[3,4]])
t_2D

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [22]:
E_1 = tf.Variable([[1,2],[3,4]])
E_1 + 10 , E_1 * 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>)

In [23]:
# Faster version on GP

tf.math.multiply(E_1,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [24]:
# Matrix Multiplication

E_1 = tf.Variable([[1,2],[3,4]])
E_2 = tf.Variable([[1,1],[2,2]])

M = tf.matmul(E_1,E_2)
M

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  5],
       [11, 11]], dtype=int32)>

In [25]:
# Eelementwise multiplication

M_2 = E_1 * E_2
M_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [26]:
# Matrix Multiplication in python using @

M_3 = E_1 @ E_2
M_3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  5],
       [11, 11]], dtype=int32)>

In [27]:
tf.transpose(tf.constant([[1,2,3,4],[5,6,7,8]]))

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)>

In [28]:
# tensor Multiplication is more general for more information look at https://www.tensorflow.org/api_docs/python/tf/tensordot

M_4 = tf.tensordot(E_1,E_2,axes=[[1],[0]])
M_4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  5],
       [11, 11]], dtype=int32)>

In [36]:
D =tf.constant([[1,2,-2],[4,2,7]])
tf.abs(D),tf.reduce_min(D),tf.reduce_max(D),tf.reduce_sum(D)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [4, 2, 7]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=14>)

In [41]:
import tensorflow_probability as tfp

tfp.stats.variance(D), tf.math.reduce_variance(tf.cast(D, dtype=tf.float32))

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, 20], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=7.555556>)

In [44]:
C = tf.random.uniform(shape=[10])
C

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.37664938, 0.7430246 , 0.69035363, 0.97365904, 0.0374527 ,
       0.27133918, 0.19803417, 0.67543113, 0.73922336, 0.02532101],
      dtype=float32)>

In [45]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [46]:
G = tf.constant(   tf.random.uniform(shape=[10]) , shape = [1,1,5,2,1,1])
G

<tf.Tensor: shape=(1, 1, 5, 2, 1, 1), dtype=float32, numpy=
array([[[[[[0.43969548]],

          [[0.56962574]]],


         [[[0.4745288 ]],

          [[0.79413843]]],


         [[[0.2821287 ]],

          [[0.7634276 ]]],


         [[[0.06374049]],

          [[0.8748003 ]]],


         [[[0.0087173 ]],

          [[0.29593766]]]]]], dtype=float32)>

In [47]:
G_squezed = tf.squeeze(G)
G_squezed

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.43969548, 0.56962574],
       [0.4745288 , 0.79413843],
       [0.2821287 , 0.7634276 ],
       [0.06374049, 0.8748003 ],
       [0.0087173 , 0.29593766]], dtype=float32)>

In [56]:
L = [0,1,5]
tf.one_hot(L,depth=7)

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [57]:
H =tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [64]:
B = np.array([1,2,3,4])
A = tf.constant(B)
A , np.array(A), A.numpy(), A.numpy()[2]

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>,
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4]),
 3)

In [65]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]