<a href="https://colab.research.google.com/github/caghamohammadi/Tensorflow_tutorial/blob/main/Session_15_Creating_your_first_tensors_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [9]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [10]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
matrix.ndim

2

In [6]:
tensor_example = tf.constant([ [[1,2],[3,4]] , [[1,2],[4,5]] , [[1,2],[6,7]] ])
tensor_example

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [4, 5]],

       [[1, 2],
        [6, 7]]], dtype=int32)>

In [7]:
tensor_example.ndim

3

In [9]:
constant_tensor = tf.constant([2,3])
changable_tensor = tf.Variable([2,3])



constant_tensor, changable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [11]:
changable_tensor[0].assign(5)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 3], dtype=int32)>